<?php

/**
 * @file
 * Contains offer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function offer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the offer module.
    case 'help.page.offer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Main module for the offer platform') . '</p>';
      return $output;

    default:
  }
}
